import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import { QueryProvider } from "./provider/querry-provider";
import { Toaster } from "sonner";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, height=device-height, initial-scale=1"
        />
      </head>
      <body>
        <div>
          <Provider>
            <QueryProvider>
              <Toaster />
              <Header />
              <main className="bg-page-gradient pt-navigation-height">
                {children}
              </main>
              <Footer />
            </QueryProvider>
          </Provider>
        </div>
      </body>
    </html>
  );
}
